version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
      MYSQL_DATABASE: furnituredb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  furniture_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db

volumes:
  mysql-data:
