version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: furnituredb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  furniture_app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
      - furniture_app

volumes:
  postgres-data: